CREATE TABLE Models (
	ModelID INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	ModelName NVARCHAR(150) NOT NULL
);

CREATE TABLE Computers (
	ComputerID INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	ComputerModelId INT NOT NULL FOREIGN KEY REFERENCES Models(ModelID),
	ComputerType NVARCHAR(1) NOT NULL,
	ComputerName NVARCHAR(150) NOT NULL,
	ComputerPrice DECIMAL(18,2) NOT NULL
);

CREATE TABLE Clients (
	ClientID INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	ClientName NVARCHAR(150) NOT NULL,
	ClientEmail NVARCHAR(150) NOT NULL,
	ClientPhone NVARCHAR(150) NOT NULL,
	ClientGender NVARCHAR(1) NOT NULL
);

CREATE TABLE Reservations (
	ReservationID INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	ClientID INT NOT NULL FOREIGN KEY REFERENCES Clients(ClientID),
	ComputerID INT NOT NULL FOREIGN KEY REFERENCES Computers(ComputerID),
	PriceToPay DECIMAL(18,2) NOT NULL,
	Payed BIT DEFAULT 0,
);